Implemented Reward Tier Rankup
CreativeSolutionsGroup/smart-events-api pull request #71
Opened 2022-11-21 22:23 UTC by JacksonIsenhower

Implemented method for User reward tier rankups and added reward_tier to the User model.
Closes #63

2022-11-23 15:56 UTC, SpBills requested changes

2022-11-23 15:56 UTC, SpBills commented on src/models/User.ts
> +  reward_tier?: ObjectId;
Change this to be `string | RewardTier`. ObjectIDs are only a concept in the schema, and we prefer to use `string` in the actual interface.

2022-11-28 04:56 UTC, JacksonIsenhower commented on src/models/User.ts
> +  reward_tier?: ObjectId;
Changed this and the corresponding assignment in the API.

2022-11-28 15:01 UTC, SpBills approved these changes
LGTM

2022-11-28 15:02 UTC, merged